<?php

namespace ContainerCiKzPp7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5b8YcS7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5b8YcS7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5b8YcS7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assetCategory' => ['privates', '.errored..service_locator.5b8YcS7.App\\Entity\\AssetCategory', NULL, 'Cannot autowire service ".service_locator.5b8YcS7": it needs an instance of "App\\Entity\\AssetCategory" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'assetCategory' => 'App\\Entity\\AssetCategory',
            'em' => '?',
        ]);
    }
}
