<?php

namespace ContainerCiKzPp7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YmwHpEOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YmwHpEO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YmwHpEO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assetCategoryRepository' => ['privates', 'App\\Repository\\AssetCategoryRepository', 'getAssetCategoryRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'assetCategoryRepository' => 'App\\Repository\\AssetCategoryRepository',
            'serializer' => '?',
        ]);
    }
}
