<?php

namespace ContainerCiKzPp7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsset2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R6mrhF_.App\Entity\Asset' shared service.
     *
     * @return \App\Entity\Asset
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.R6mrhF_": it needs an instance of "App\\Entity\\Asset" but this type has been excluded in "config/services.yaml".');
    }
}
