<?php

namespace ContainerCiKzPp7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5b8YcS7.App\Entity\AssetCategory' shared service.
     *
     * @return \App\Entity\AssetCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5b8YcS7": it needs an instance of "App\\Entity\\AssetCategory" but this type has been excluded in "config/services.yaml".');
    }
}
