<?php

namespace Container6RV8BuQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LQ6UU3SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LQ6UU3S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LQ6UU3S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assetCategoryRepository' => ['privates', 'App\\Repository\\AssetCategoryRepository', 'getAssetCategoryRepositoryService', true],
            'currentAsset' => ['privates', '.errored..service_locator.LQ6UU3S.App\\Entity\\Asset', NULL, 'Cannot autowire service ".service_locator.LQ6UU3S": it needs an instance of "App\\Entity\\Asset" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'assetCategoryRepository' => 'App\\Repository\\AssetCategoryRepository',
            'currentAsset' => 'App\\Entity\\Asset',
            'em' => '?',
            'serializer' => '?',
        ]);
    }
}
