<?php

namespace Container6RV8BuQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SarZ3RDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SarZ3RD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SarZ3RD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AssetCategoryController::createAssetCategory' => ['privates', '.service_locator.OvD6SVk', 'get_ServiceLocator_OvD6SVkService', true],
            'App\\Controller\\AssetCategoryController::deleteAssetCategory' => ['privates', '.service_locator.5b8YcS7', 'get_ServiceLocator_5b8YcS7Service', true],
            'App\\Controller\\AssetCategoryController::getAssetCategoryDetail' => ['privates', '.service_locator.YmwHpEO', 'get_ServiceLocator_YmwHpEOService', true],
            'App\\Controller\\AssetCategoryController::getAssetCategoryList' => ['privates', '.service_locator.YmwHpEO', 'get_ServiceLocator_YmwHpEOService', true],
            'App\\Controller\\AssetCategoryController::updateAssetCategory' => ['privates', '.service_locator.TA688Zy', 'get_ServiceLocator_TA688ZyService', true],
            'App\\Controller\\AssetController::createAsset' => ['privates', '.service_locator.K_.RrFG', 'get_ServiceLocator_K_RrFGService', true],
            'App\\Controller\\AssetController::deleteAsset' => ['privates', '.service_locator.R6mrhF_', 'get_ServiceLocator_R6mrhFService', true],
            'App\\Controller\\AssetController::getAssetDetail' => ['privates', '.service_locator.TCiP7tb', 'get_ServiceLocator_TCiP7tbService', true],
            'App\\Controller\\AssetController::getAssetList' => ['privates', '.service_locator.TCiP7tb', 'get_ServiceLocator_TCiP7tbService', true],
            'App\\Controller\\AssetController::updateAsset' => ['privates', '.service_locator.LQ6UU3S', 'get_ServiceLocator_LQ6UU3SService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AssetCategoryController:createAssetCategory' => ['privates', '.service_locator.OvD6SVk', 'get_ServiceLocator_OvD6SVkService', true],
            'App\\Controller\\AssetCategoryController:deleteAssetCategory' => ['privates', '.service_locator.5b8YcS7', 'get_ServiceLocator_5b8YcS7Service', true],
            'App\\Controller\\AssetCategoryController:getAssetCategoryDetail' => ['privates', '.service_locator.YmwHpEO', 'get_ServiceLocator_YmwHpEOService', true],
            'App\\Controller\\AssetCategoryController:getAssetCategoryList' => ['privates', '.service_locator.YmwHpEO', 'get_ServiceLocator_YmwHpEOService', true],
            'App\\Controller\\AssetCategoryController:updateAssetCategory' => ['privates', '.service_locator.TA688Zy', 'get_ServiceLocator_TA688ZyService', true],
            'App\\Controller\\AssetController:createAsset' => ['privates', '.service_locator.K_.RrFG', 'get_ServiceLocator_K_RrFGService', true],
            'App\\Controller\\AssetController:deleteAsset' => ['privates', '.service_locator.R6mrhF_', 'get_ServiceLocator_R6mrhFService', true],
            'App\\Controller\\AssetController:getAssetDetail' => ['privates', '.service_locator.TCiP7tb', 'get_ServiceLocator_TCiP7tbService', true],
            'App\\Controller\\AssetController:getAssetList' => ['privates', '.service_locator.TCiP7tb', 'get_ServiceLocator_TCiP7tbService', true],
            'App\\Controller\\AssetController:updateAsset' => ['privates', '.service_locator.LQ6UU3S', 'get_ServiceLocator_LQ6UU3SService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AssetCategoryController::createAssetCategory' => '?',
            'App\\Controller\\AssetCategoryController::deleteAssetCategory' => '?',
            'App\\Controller\\AssetCategoryController::getAssetCategoryDetail' => '?',
            'App\\Controller\\AssetCategoryController::getAssetCategoryList' => '?',
            'App\\Controller\\AssetCategoryController::updateAssetCategory' => '?',
            'App\\Controller\\AssetController::createAsset' => '?',
            'App\\Controller\\AssetController::deleteAsset' => '?',
            'App\\Controller\\AssetController::getAssetDetail' => '?',
            'App\\Controller\\AssetController::getAssetList' => '?',
            'App\\Controller\\AssetController::updateAsset' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AssetCategoryController:createAssetCategory' => '?',
            'App\\Controller\\AssetCategoryController:deleteAssetCategory' => '?',
            'App\\Controller\\AssetCategoryController:getAssetCategoryDetail' => '?',
            'App\\Controller\\AssetCategoryController:getAssetCategoryList' => '?',
            'App\\Controller\\AssetCategoryController:updateAssetCategory' => '?',
            'App\\Controller\\AssetController:createAsset' => '?',
            'App\\Controller\\AssetController:deleteAsset' => '?',
            'App\\Controller\\AssetController:getAssetDetail' => '?',
            'App\\Controller\\AssetController:getAssetList' => '?',
            'App\\Controller\\AssetController:updateAsset' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
