<?php

namespace Container6RV8BuQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TA688ZyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TA688Zy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TA688Zy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'currentAssetCategory' => ['privates', '.errored..service_locator.TA688Zy.App\\Entity\\AssetCategory', NULL, 'Cannot autowire service ".service_locator.TA688Zy": it needs an instance of "App\\Entity\\AssetCategory" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'currentAssetCategory' => 'App\\Entity\\AssetCategory',
            'em' => '?',
            'serializer' => '?',
        ]);
    }
}
